train: D:\Users\MasonFrancis\OneDrive\Coding\photocaptureforai\working\in\images\train\
val:  D:\Users\MasonFrancis\OneDrive\Coding\photocaptureforai\working\in\images\val
test: D:\Users\MasonFrancis\OneDrive\Coding\photocaptureforai\working\in\images\test\

# number of classes
nc: 1

# class names
names: ["controlpanel"]
